package report

import (
	"os"
	"strings"
	"testing"
)

func TestGenerateMarkdownReport(t *testing.T) {
	profile := createTestProfile()

	tempFile, err := os.CreateTemp("", "report_*.md")
	if err != nil {
		t.Fatalf("Failed to create temp file: %v", err)
	}
	defer os.Remove(tempFile.Name())
	tempFile.Close()

	err = GenerateMarkdownReport(profile, tempFile.Name())
	if err != nil {
		t.Fatalf("GenerateMarkdownReport failed: %v", err)
	}

	content, err := os.ReadFile(tempFile.Name())
	if err != nil {
		t.Fatalf("Failed to read report file: %v", err)
	}

	mdContent := string(content)

	expectedStrings := []string{
		"# DataSleuth Profile: test.csv",
		"## Dataset Quality Score: 85/100",
		"## Dataset Summary",
		"| Rows | 1,000 |",
		"| Columns | 3 |",
		"| Missing cells |",
		"## Quality Issues",
		"## Column Details",
		"### test_str",
		"### test_int",
		"### test_float",
		"**Type:** float",
		"**Top Values:**",
		"Generated by DataSleuth",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(mdContent, expected) {
			t.Errorf("Expected Markdown to contain '%s'", expected)
		}
	}
}
